[programs.localnet]
auction = "AsKrbegKTCnZvmV2Dyw1kUpSps2vMrevpeiJkjex4Mru"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/john/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
