[programs.localnet]
anchor_nft = "6qZt2RG8og8DKkjXFi3aQCWMg9pkiUUBb4s6nbGgMPry"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/john/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
