[package]
name = "core"
version = "0.1.0"
description = "Created with Anchor"
edition = "2018"

[lib]
crate-type = ["lib"]
path = "src/lib.rs"

[dependencies]
anchor-client = "~0.20.1"
shellexpand = "~2.1.0"
serde_json = "~1.0"
solana-program-test = "~1.9.5"
solana-program = "~1.9.5"
solana-sdk = "~1.9.5" 
spl-token = { version = "~3.2",  features = ["no-entrypoint"] }
spl-associated-token-account = { version = "~1.0.3",  features = ["no-entrypoint"] }
mpl-token-metadata = { version="~1.1.0", features = [ "no-entrypoint" ] }
mpl-token-vault = { path = "../../programs/token-vault", features = [ "no-entrypoint" ] }
rand = "~0.7.3"
num = "~0.4"
num-derive = "~0.3"
num-traits = "~0.2"
borsh = "~0.9.1"